[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "pkg-versioned"
version = "1.0.0"
description = "Workspace member with an explicit version"
requires-python = ">=3.11"
readme = "README.md"
